serverName: CS++
channelID: 1053499749443059814
morningEmoji: "â˜€ï¸ "
badEmoji: "ğŸ¤¬"
easterEggs:
- string: "cheesed to meet you"
  emoji: "ğŸ§€"
- string: "good corning"
  emoji: "ğŸŒ½"
- string: "mroning"
  emoji: "ğŸ¤¡"
- string: "programmer socks"
  emoji: "ğŸ¤¤"
- string: "guys being dudes"
  emoji: "ğŸ‘¨â€â¤ï¸â€ğŸ’‹â€ğŸ‘¨"
