name: Json-Validate
run-name: ${{ github.actor }} PR being linted for code cleanliness
on: [pull_request]
jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - run: echo "Checked out into ${{ github.repository }} on branch ${{ github.ref }}"
      - run: python -mjson.tool **/*.json
